-- MySQL Script generated by MySQL Workbench
-- Mon Sep 23 17:50:08 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema inventorydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema inventorydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `inventorydb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `inventorydb` ;

-- -----------------------------------------------------
-- Table `inventorydb`.`brand`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`brand` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `summary` TINYTEXT NULL DEFAULT NULL,
  `title` VARCHAR(75) NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `meta_title` VARCHAR(100) NULL DEFAULT NULL,
  `slug` VARCHAR(100) NOT NULL,
  `title` VARCHAR(75) NOT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`common_object`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`common_object` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `details` VARCHAR(255) NULL DEFAULT NULL,
  `object_type` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capital` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `continent` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `nationality` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `details` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`user` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `intro` TINYTEXT NULL DEFAULT NULL,
  `last_login` DATETIME(6) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `middle_name` VARCHAR(50) NULL DEFAULT NULL,
  `mobile` VARCHAR(15) NULL DEFAULT NULL,
  `password` VARCHAR(255) NOT NULL,
  `password_hash` VARCHAR(255) NULL DEFAULT NULL,
  `profile` TEXT NULL DEFAULT NULL,
  `registered_at` DATETIME(6) NULL DEFAULT NULL,
  `username` VARCHAR(50) NOT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  `roleid` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKsb8bbouer5wak8vyiiy4pf2bx` (`username` ASC) VISIBLE,
  UNIQUE INDEX `UKob8kqyqqgmefl0aco34akdtpe` (`email` ASC) VISIBLE,
  UNIQUE INDEX `UKcnjwxx5favk5ycqajjt17fwy1` (`mobile` ASC) VISIBLE,
  INDEX `FK2ovmsl4hvm5vu1w8i308r5j6w` (`roleid` ASC) VISIBLE,
  CONSTRAINT `FK2ovmsl4hvm5vu1w8i308r5j6w`
    FOREIGN KEY (`roleid`)
    REFERENCES `inventorydb`.`role` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`state`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`state` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capital` VARCHAR(255) NULL DEFAULT NULL,
  `code` VARCHAR(255) NULL DEFAULT NULL,
  `countryid` INT NULL DEFAULT NULL,
  `details` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK26mi9hxhe1phwyqkvwb4ygot5` (`countryid` ASC) VISIBLE,
  CONSTRAINT `FK26mi9hxhe1phwyqkvwb4ygot5`
    FOREIGN KEY (`countryid`)
    REFERENCES `inventorydb`.`country` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 32
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`supplier` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `city` VARCHAR(255) NULL DEFAULT NULL,
  `countryid` INT NULL DEFAULT NULL,
  `details` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `mobile` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `stateid` INT NULL DEFAULT NULL,
  `website` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKan3bwr38w0wfolb0s19xdh9xi` (`countryid` ASC) VISIBLE,
  INDEX `FKdksgl156r0b3rjw74nuna1bqt` (`stateid` ASC) VISIBLE,
  CONSTRAINT `FKan3bwr38w0wfolb0s19xdh9xi`
    FOREIGN KEY (`countryid`)
    REFERENCES `inventorydb`.`country` (`id`),
  CONSTRAINT `FKdksgl156r0b3rjw74nuna1bqt`
    FOREIGN KEY (`stateid`)
    REFERENCES `inventorydb`.`state` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`order` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `discount` FLOAT NOT NULL,
  `grand_total` FLOAT NOT NULL,
  `item_discount` FLOAT NOT NULL,
  `promo` VARCHAR(50) NULL DEFAULT NULL,
  `shipping` FLOAT NOT NULL,
  `sub_total` FLOAT NOT NULL,
  `tax` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  `orderstatusid` BIGINT NULL DEFAULT NULL,
  `ordertypeid` BIGINT NULL DEFAULT NULL,
  `addressid` BIGINT NULL DEFAULT NULL,
  `supplierid` BIGINT NULL DEFAULT NULL,
  `status` SMALLINT NOT NULL,
  `type` SMALLINT NOT NULL,
  `customerid` BIGINT NULL DEFAULT NULL,
  `remarks` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK4exv4cak3vmfc3o201kcrqdd6` (`orderstatusid` ASC) VISIBLE,
  INDEX `FKc16ufbpku62b16c9r6ggy6pdp` (`ordertypeid` ASC) VISIBLE,
  INDEX `FKni76c1iqfkmj83si3ceb4fac4` (`addressid` ASC) VISIBLE,
  INDEX `FKjdu20d1o4f721iduofth88qry` (`supplierid` ASC) VISIBLE,
  INDEX `FKcpl0mjoeqhxvgeeeq5piwpd3i` (`user_id` ASC) VISIBLE,
  INDEX `FK1t7f2e7ygr5axjy3500yofr4s` (`customerid` ASC) VISIBLE,
  CONSTRAINT `FK1t7f2e7ygr5axjy3500yofr4s`
    FOREIGN KEY (`customerid`)
    REFERENCES `inventorydb`.`customer` (`id`),
  CONSTRAINT `FK4exv4cak3vmfc3o201kcrqdd6`
    FOREIGN KEY (`orderstatusid`)
    REFERENCES `inventorydb`.`common_object` (`id`),
  CONSTRAINT `FKc16ufbpku62b16c9r6ggy6pdp`
    FOREIGN KEY (`ordertypeid`)
    REFERENCES `inventorydb`.`common_object` (`id`),
  CONSTRAINT `FKcpl0mjoeqhxvgeeeq5piwpd3i`
    FOREIGN KEY (`user_id`)
    REFERENCES `inventorydb`.`user` (`id`),
  CONSTRAINT `FKjdu20d1o4f721iduofth88qry`
    FOREIGN KEY (`supplierid`)
    REFERENCES `inventorydb`.`supplier` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 45
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`customer` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `first_name` VARCHAR(50) NULL DEFAULT NULL,
  `last_name` VARCHAR(50) NULL DEFAULT NULL,
  `line1` VARCHAR(50) NULL DEFAULT NULL,
  `line2` VARCHAR(50) NULL DEFAULT NULL,
  `middle_name` VARCHAR(50) NULL DEFAULT NULL,
  `mobile` VARCHAR(15) NULL DEFAULT NULL,
  `province` VARCHAR(50) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `order_id` BIGINT NULL DEFAULT NULL,
  `user_id` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKmla61fe7ppx069ykcgro5u9j1` (`order_id` ASC) VISIBLE,
  INDEX `FKj8dlm21j202cadsbfkoem0s58` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKj8dlm21j202cadsbfkoem0s58`
    FOREIGN KEY (`user_id`)
    REFERENCES `inventorydb`.`user` (`id`),
  CONSTRAINT `FKmla61fe7ppx069ykcgro5u9j1`
    FOREIGN KEY (`order_id`)
    REFERENCES `inventorydb`.`order` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`sub_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`sub_category` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `categoryid` BIGINT NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK30d25wahq94ce4fjk82agyqu4` (`categoryid` ASC) VISIBLE,
  CONSTRAINT `FK30d25wahq94ce4fjk82agyqu4`
    FOREIGN KEY (`categoryid`)
    REFERENCES `inventorydb`.`category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 34
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`product` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `categoryid` BIGINT NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `created_at` DATETIME(6) NOT NULL,
  `subcategoryid` BIGINT NULL DEFAULT NULL,
  `summary` TINYTEXT NULL DEFAULT NULL,
  `title` VARCHAR(75) NOT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK4ort9abhumpx4t2mlngljr1vi` (`categoryid` ASC) VISIBLE,
  INDEX `FKq01nemr5y2qcsxjwkvwvl84ht` (`subcategoryid` ASC) VISIBLE,
  CONSTRAINT `FK4ort9abhumpx4t2mlngljr1vi`
    FOREIGN KEY (`categoryid`)
    REFERENCES `inventorydb`.`category` (`id`),
  CONSTRAINT `FKq01nemr5y2qcsxjwkvwvl84ht`
    FOREIGN KEY (`subcategoryid`)
    REFERENCES `inventorydb`.`sub_category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 33
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `available` SMALLINT NULL DEFAULT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `defective` SMALLINT NULL DEFAULT NULL,
  `discount` FLOAT NULL DEFAULT NULL,
  `mrp` FLOAT NULL DEFAULT NULL,
  `price` FLOAT NULL DEFAULT NULL,
  `quantity` SMALLINT NULL DEFAULT NULL,
  `sku` VARCHAR(100) NULL DEFAULT NULL,
  `sold` SMALLINT NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  `orderid` BIGINT NULL DEFAULT NULL,
  `productid` BIGINT NULL DEFAULT NULL,
  `subcategoryid` BIGINT NULL DEFAULT NULL,
  `supplierid` BIGINT NULL DEFAULT NULL,
  `brandid` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKp0xj13bmpja9m7qhxo65c43jn` (`orderid` ASC) VISIBLE,
  INDEX `FK2ltdskt1syqkei1yxj8c1eiug` (`productid` ASC) VISIBLE,
  INDEX `FKshpm64cs8mnx9c05nxpv6jato` (`subcategoryid` ASC) VISIBLE,
  INDEX `FKfvmin1fiohkqu97bts6231hlv` (`brandid` ASC) VISIBLE,
  INDEX `FKrjgpa71wev1cpp5veexd4fdoi` (`supplierid` ASC) VISIBLE,
  CONSTRAINT `FK2ltdskt1syqkei1yxj8c1eiug`
    FOREIGN KEY (`productid`)
    REFERENCES `inventorydb`.`product` (`id`),
  CONSTRAINT `FKfvmin1fiohkqu97bts6231hlv`
    FOREIGN KEY (`brandid`)
    REFERENCES `inventorydb`.`brand` (`id`),
  CONSTRAINT `FKp0xj13bmpja9m7qhxo65c43jn`
    FOREIGN KEY (`orderid`)
    REFERENCES `inventorydb`.`order` (`id`),
  CONSTRAINT `FKrjgpa71wev1cpp5veexd4fdoi`
    FOREIGN KEY (`supplierid`)
    REFERENCES `inventorydb`.`supplier` (`id`),
  CONSTRAINT `FKshpm64cs8mnx9c05nxpv6jato`
    FOREIGN KEY (`subcategoryid`)
    REFERENCES `inventorydb`.`sub_category` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`login_request`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`login_request` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`order_item` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `discount` FLOAT NOT NULL,
  `quantity` SMALLINT NOT NULL,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  `itemid` BIGINT NULL DEFAULT NULL,
  `orderid` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKrffp1wvvbgxi3qf9u125913j5` (`itemid` ASC) VISIBLE,
  INDEX `FKq7uws5g6cw0vj8v400wl1pm1b` (`orderid` ASC) VISIBLE,
  CONSTRAINT `FKq7uws5g6cw0vj8v400wl1pm1b`
    FOREIGN KEY (`orderid`)
    REFERENCES `inventorydb`.`order` (`id`),
  CONSTRAINT `FKrffp1wvvbgxi3qf9u125913j5`
    FOREIGN KEY (`itemid`)
    REFERENCES `inventorydb`.`item` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 13
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`product_meta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`product_meta` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `content` TEXT NULL DEFAULT NULL,
  `key` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `inventorydb`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `inventorydb`.`transaction` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `created_by` VARCHAR(255) NULL DEFAULT NULL,
  `created_date` DATETIME(6) NULL DEFAULT NULL,
  `last_modified_by` VARCHAR(255) NULL DEFAULT NULL,
  `last_modified_date` DATETIME(6) NULL DEFAULT NULL,
  `content` TEXT NULL DEFAULT NULL,
  `orderid` BIGINT NULL DEFAULT NULL,
  `transaction_code` VARCHAR(255) NULL DEFAULT NULL,
  `transactionmodeid` BIGINT NULL DEFAULT NULL,
  `transactionstatusid` BIGINT NULL DEFAULT NULL,
  `transactiontypeid` BIGINT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKfh94v0xm1jhxpcoiqhn5nut8e` (`orderid` ASC) VISIBLE,
  INDEX `FK7vg3oj40l48rw1h4wr1pnwc7p` (`transactionmodeid` ASC) VISIBLE,
  INDEX `FKhjjnk9jbun391g3rtus6wkk7w` (`transactionstatusid` ASC) VISIBLE,
  INDEX `FKl2yebe34du3ssufvt81vuwk2p` (`transactiontypeid` ASC) VISIBLE,
  CONSTRAINT `FK7vg3oj40l48rw1h4wr1pnwc7p`
    FOREIGN KEY (`transactionmodeid`)
    REFERENCES `inventorydb`.`common_object` (`id`),
  CONSTRAINT `FKfh94v0xm1jhxpcoiqhn5nut8e`
    FOREIGN KEY (`orderid`)
    REFERENCES `inventorydb`.`order` (`id`),
  CONSTRAINT `FKhjjnk9jbun391g3rtus6wkk7w`
    FOREIGN KEY (`transactionstatusid`)
    REFERENCES `inventorydb`.`common_object` (`id`),
  CONSTRAINT `FKl2yebe34du3ssufvt81vuwk2p`
    FOREIGN KEY (`transactiontypeid`)
    REFERENCES `inventorydb`.`common_object` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
